### ISSUE TITLE
Enhancement: Allow for greater accuracy

### ISSUE THREAD

**Issue by pensionado** [MarcoBuster/WUndergroundPWS-API#1]
Thanks for this excellent bit of code. Could you enhance it further by adding `numericPrecision: decimal` to the request URL, which allow for many measurements reporting back with decimals, rather then integers. Hacked my bit of code for it and works like a charm.

**Comment by MarcoBuster** [comment]
Hi @pensionado, thank you! Would you like to open a pull request?

**Comment by pensionado** [comment]
Git is sort of alien to me, I made the change directly in the installed package. Tried to do it, by cloning the project, create a new branch, make the mods and put them back, but I am doing something wrong, get a not authorised. trying to push the branch back, so I can create a pull request, I think that would be the next step.

**Comment by MarcoBuster** [comment]
@pensionado yeah, you should create a pull request. I suggest you to read this guide: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
Do this as an occasion to learn some git!
